version: '3.7'
#https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4-address-ipv6-address 

services:
  server:
    image: gocd/gocd-server:v20.1.0
#    build: ./server
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 8153-8154:8153-8154
    environment:
      - GOCD_PLUGIN_INSTALL_elastic-agent-skeleton-plugin=https://github.com/maxbalan/elastic-agent-skeleton-plugin/raw/master/target/elastic-agent-skeleton-plugin-1.jar

networks:
  backend:
    driver: bridge
  testing:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 175.20.222.0/24
